/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthSetupRouteImport } from './routes/auth/setup'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeApiKeysRouteImport } from './routes/home/api-keys'
import { Route as HomeProfileRouteImport } from './routes/home/profile'
import { Route as AdminAnnouncementsIndexRouteImport } from './routes/admin/announcements/index'
import { Route as AdminAnnouncementsAnnouncementIdRouteImport } from './routes/admin/announcements/$announcementId'
import { Route as AdminContactsIndexRouteImport } from './routes/admin/contacts/index'
import { Route as AdminContactsContactIdRouteImport } from './routes/admin/contacts/$contactId'
import { Route as AdminFeedbackIndexRouteImport } from './routes/admin/feedback/index'
import { Route as AdminFeedbackFeedbackIdRouteImport } from './routes/admin/feedback/$feedbackId'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as HomeAnnouncementsIndexRouteImport } from './routes/home/announcements/index'
import { Route as HomeAnnouncementsAnnouncementIdRouteImport } from './routes/home/announcements/$announcementId'
import { Route as HomeFeedbackIndexRouteImport } from './routes/home/feedback/index'
import { Route as HomeFeedbackFeedbackIdRouteImport } from './routes/home/feedback/$feedbackId'
import { Route as HomeNotesIndexRouteImport } from './routes/home/notes/index'
import { Route as HomeNotesNoteIdRouteImport } from './routes/home/notes/$noteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeApiKeysRoute = HomeApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeProfileRoute = HomeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AdminAnnouncementsIndexRoute = AdminAnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnnouncementsAnnouncementIdRoute =
  AdminAnnouncementsAnnouncementIdRouteImport.update({
    id: '/announcements/$announcementId',
    path: '/announcements/$announcementId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminContactsIndexRoute = AdminContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContactsContactIdRoute = AdminContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeedbackIndexRoute = AdminFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeedbackFeedbackIdRoute = AdminFeedbackFeedbackIdRouteImport.update({
  id: '/feedback/$feedbackId',
  path: '/feedback/$feedbackId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const HomeAnnouncementsIndexRoute = HomeAnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAnnouncementsAnnouncementIdRoute =
  HomeAnnouncementsAnnouncementIdRouteImport.update({
    id: '/announcements/$announcementId',
    path: '/announcements/$announcementId',
    getParentRoute: () => HomeRouteRoute,
  } as any)
const HomeFeedbackIndexRoute = HomeFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeFeedbackFeedbackIdRoute = HomeFeedbackFeedbackIdRouteImport.update({
  id: '/feedback/$feedbackId',
  path: '/feedback/$feedbackId',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeNotesIndexRoute = HomeNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeNotesNoteIdRoute = HomeNotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => HomeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/auth/setup': typeof AuthSetupRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/home/api-keys': typeof HomeApiKeysRoute
  '/home/profile': typeof HomeProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/home/': typeof HomeIndexRoute
  '/admin/announcements/$announcementId': typeof AdminAnnouncementsAnnouncementIdRoute
  '/admin/contacts/$contactId': typeof AdminContactsContactIdRoute
  '/admin/feedback/$feedbackId': typeof AdminFeedbackFeedbackIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/home/announcements/$announcementId': typeof HomeAnnouncementsAnnouncementIdRoute
  '/home/feedback/$feedbackId': typeof HomeFeedbackFeedbackIdRoute
  '/home/notes/$noteId': typeof HomeNotesNoteIdRoute
  '/admin/announcements/': typeof AdminAnnouncementsIndexRoute
  '/admin/contacts/': typeof AdminContactsIndexRoute
  '/admin/feedback/': typeof AdminFeedbackIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/home/announcements/': typeof HomeAnnouncementsIndexRoute
  '/home/feedback/': typeof HomeFeedbackIndexRoute
  '/home/notes/': typeof HomeNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/auth/setup': typeof AuthSetupRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/home/api-keys': typeof HomeApiKeysRoute
  '/home/profile': typeof HomeProfileRoute
  '/admin': typeof AdminIndexRoute
  '/home': typeof HomeIndexRoute
  '/admin/announcements/$announcementId': typeof AdminAnnouncementsAnnouncementIdRoute
  '/admin/contacts/$contactId': typeof AdminContactsContactIdRoute
  '/admin/feedback/$feedbackId': typeof AdminFeedbackFeedbackIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/home/announcements/$announcementId': typeof HomeAnnouncementsAnnouncementIdRoute
  '/home/feedback/$feedbackId': typeof HomeFeedbackFeedbackIdRoute
  '/home/notes/$noteId': typeof HomeNotesNoteIdRoute
  '/admin/announcements': typeof AdminAnnouncementsIndexRoute
  '/admin/contacts': typeof AdminContactsIndexRoute
  '/admin/feedback': typeof AdminFeedbackIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/home/announcements': typeof HomeAnnouncementsIndexRoute
  '/home/feedback': typeof HomeFeedbackIndexRoute
  '/home/notes': typeof HomeNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/auth/setup': typeof AuthSetupRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/home/api-keys': typeof HomeApiKeysRoute
  '/home/profile': typeof HomeProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/home/': typeof HomeIndexRoute
  '/admin/announcements/$announcementId': typeof AdminAnnouncementsAnnouncementIdRoute
  '/admin/contacts/$contactId': typeof AdminContactsContactIdRoute
  '/admin/feedback/$feedbackId': typeof AdminFeedbackFeedbackIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/home/announcements/$announcementId': typeof HomeAnnouncementsAnnouncementIdRoute
  '/home/feedback/$feedbackId': typeof HomeFeedbackFeedbackIdRoute
  '/home/notes/$noteId': typeof HomeNotesNoteIdRoute
  '/admin/announcements/': typeof AdminAnnouncementsIndexRoute
  '/admin/contacts/': typeof AdminContactsIndexRoute
  '/admin/feedback/': typeof AdminFeedbackIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/home/announcements/': typeof HomeAnnouncementsIndexRoute
  '/home/feedback/': typeof HomeFeedbackIndexRoute
  '/home/notes/': typeof HomeNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/home'
    | '/contact'
    | '/help'
    | '/auth/setup'
    | '/auth/sign-in'
    | '/home/api-keys'
    | '/home/profile'
    | '/admin/'
    | '/home/'
    | '/admin/announcements/$announcementId'
    | '/admin/contacts/$contactId'
    | '/admin/feedback/$feedbackId'
    | '/admin/users/$userId'
    | '/home/announcements/$announcementId'
    | '/home/feedback/$feedbackId'
    | '/home/notes/$noteId'
    | '/admin/announcements/'
    | '/admin/contacts/'
    | '/admin/feedback/'
    | '/admin/users/'
    | '/home/announcements/'
    | '/home/feedback/'
    | '/home/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/help'
    | '/auth/setup'
    | '/auth/sign-in'
    | '/home/api-keys'
    | '/home/profile'
    | '/admin'
    | '/home'
    | '/admin/announcements/$announcementId'
    | '/admin/contacts/$contactId'
    | '/admin/feedback/$feedbackId'
    | '/admin/users/$userId'
    | '/home/announcements/$announcementId'
    | '/home/feedback/$feedbackId'
    | '/home/notes/$noteId'
    | '/admin/announcements'
    | '/admin/contacts'
    | '/admin/feedback'
    | '/admin/users'
    | '/home/announcements'
    | '/home/feedback'
    | '/home/notes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/home'
    | '/contact'
    | '/help'
    | '/auth/setup'
    | '/auth/sign-in'
    | '/home/api-keys'
    | '/home/profile'
    | '/admin/'
    | '/home/'
    | '/admin/announcements/$announcementId'
    | '/admin/contacts/$contactId'
    | '/admin/feedback/$feedbackId'
    | '/admin/users/$userId'
    | '/home/announcements/$announcementId'
    | '/home/feedback/$feedbackId'
    | '/home/notes/$noteId'
    | '/admin/announcements/'
    | '/admin/contacts/'
    | '/admin/feedback/'
    | '/admin/users/'
    | '/home/announcements/'
    | '/home/feedback/'
    | '/home/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  HelpRoute: typeof HelpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/setup': {
      id: '/auth/setup'
      path: '/setup'
      fullPath: '/auth/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/api-keys': {
      id: '/home/api-keys'
      path: '/api-keys'
      fullPath: '/home/api-keys'
      preLoaderRoute: typeof HomeApiKeysRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/profile': {
      id: '/home/profile'
      path: '/profile'
      fullPath: '/home/profile'
      preLoaderRoute: typeof HomeProfileRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/admin/announcements/': {
      id: '/admin/announcements/'
      path: '/announcements'
      fullPath: '/admin/announcements/'
      preLoaderRoute: typeof AdminAnnouncementsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/announcements/$announcementId': {
      id: '/admin/announcements/$announcementId'
      path: '/announcements/$announcementId'
      fullPath: '/admin/announcements/$announcementId'
      preLoaderRoute: typeof AdminAnnouncementsAnnouncementIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contacts/': {
      id: '/admin/contacts/'
      path: '/contacts'
      fullPath: '/admin/contacts/'
      preLoaderRoute: typeof AdminContactsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contacts/$contactId': {
      id: '/admin/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/admin/contacts/$contactId'
      preLoaderRoute: typeof AdminContactsContactIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/feedback/': {
      id: '/admin/feedback/'
      path: '/feedback'
      fullPath: '/admin/feedback/'
      preLoaderRoute: typeof AdminFeedbackIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/feedback/$feedbackId': {
      id: '/admin/feedback/$feedbackId'
      path: '/feedback/$feedbackId'
      fullPath: '/admin/feedback/$feedbackId'
      preLoaderRoute: typeof AdminFeedbackFeedbackIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/home/announcements/': {
      id: '/home/announcements/'
      path: '/announcements'
      fullPath: '/home/announcements/'
      preLoaderRoute: typeof HomeAnnouncementsIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/announcements/$announcementId': {
      id: '/home/announcements/$announcementId'
      path: '/announcements/$announcementId'
      fullPath: '/home/announcements/$announcementId'
      preLoaderRoute: typeof HomeAnnouncementsAnnouncementIdRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/feedback/': {
      id: '/home/feedback/'
      path: '/feedback'
      fullPath: '/home/feedback/'
      preLoaderRoute: typeof HomeFeedbackIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/feedback/$feedbackId': {
      id: '/home/feedback/$feedbackId'
      path: '/feedback/$feedbackId'
      fullPath: '/home/feedback/$feedbackId'
      preLoaderRoute: typeof HomeFeedbackFeedbackIdRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/notes/': {
      id: '/home/notes/'
      path: '/notes'
      fullPath: '/home/notes/'
      preLoaderRoute: typeof HomeNotesIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/notes/$noteId': {
      id: '/home/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/home/notes/$noteId'
      preLoaderRoute: typeof HomeNotesNoteIdRouteImport
      parentRoute: typeof HomeRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnnouncementsAnnouncementIdRoute: typeof AdminAnnouncementsAnnouncementIdRoute
  AdminContactsContactIdRoute: typeof AdminContactsContactIdRoute
  AdminFeedbackFeedbackIdRoute: typeof AdminFeedbackFeedbackIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminAnnouncementsIndexRoute: typeof AdminAnnouncementsIndexRoute
  AdminContactsIndexRoute: typeof AdminContactsIndexRoute
  AdminFeedbackIndexRoute: typeof AdminFeedbackIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAnnouncementsAnnouncementIdRoute: AdminAnnouncementsAnnouncementIdRoute,
  AdminContactsContactIdRoute: AdminContactsContactIdRoute,
  AdminFeedbackFeedbackIdRoute: AdminFeedbackFeedbackIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminAnnouncementsIndexRoute: AdminAnnouncementsIndexRoute,
  AdminContactsIndexRoute: AdminContactsIndexRoute,
  AdminFeedbackIndexRoute: AdminFeedbackIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSetupRoute: typeof AuthSetupRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSetupRoute: AuthSetupRoute,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeApiKeysRoute: typeof HomeApiKeysRoute
  HomeProfileRoute: typeof HomeProfileRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HomeAnnouncementsAnnouncementIdRoute: typeof HomeAnnouncementsAnnouncementIdRoute
  HomeFeedbackFeedbackIdRoute: typeof HomeFeedbackFeedbackIdRoute
  HomeNotesNoteIdRoute: typeof HomeNotesNoteIdRoute
  HomeAnnouncementsIndexRoute: typeof HomeAnnouncementsIndexRoute
  HomeFeedbackIndexRoute: typeof HomeFeedbackIndexRoute
  HomeNotesIndexRoute: typeof HomeNotesIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeApiKeysRoute: HomeApiKeysRoute,
  HomeProfileRoute: HomeProfileRoute,
  HomeIndexRoute: HomeIndexRoute,
  HomeAnnouncementsAnnouncementIdRoute: HomeAnnouncementsAnnouncementIdRoute,
  HomeFeedbackFeedbackIdRoute: HomeFeedbackFeedbackIdRoute,
  HomeNotesNoteIdRoute: HomeNotesNoteIdRoute,
  HomeAnnouncementsIndexRoute: HomeAnnouncementsIndexRoute,
  HomeFeedbackIndexRoute: HomeFeedbackIndexRoute,
  HomeNotesIndexRoute: HomeNotesIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  ContactRoute: ContactRoute,
  HelpRoute: HelpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
